import {LanguageLocalizationModel} from '../models/languageModel';
import {DataType} from '../enums/dataType';

const localizationsTr = [
    {key: 'meta-default-title', value: 'Serkan DOĞANBAŞ | Rise TODO App', dataType: DataType.string},
    {key: 'meta-default-keyword', value: 'todo, todo app, serkan doğanbaş', dataType: DataType.string},
    {key: 'meta-default-description', value: 'Rise Frontend Assessment Project.', dataType: DataType.string},
    {key: 'meta-default-abstract', value: 'Rise Frontend Assessment Project.', dataType: DataType.string},
    {key: 'fetch-todo-priority-list', value: 'Durum verileri sunucudan alınıyor...', dataType: DataType.string},
    {key: 'validation-required', value: '\'{{name}}\' isimli alan boş bırakılamaz.', dataType: DataType.string},
    {key: 'validation-string-min', value: '\'{{name}}\' isimli alan değeri en az {{min}} karakterden oluşmalıdır.', dataType: DataType.string},
    {key: 'validation-string-max', value: '\'{{name}}\' isimli alan değeri en fazla {{max}} karakterden oluşmalıdır.', dataType: DataType.string},
    {key: 'validation-string-length', value: '\'{{name}}\' isimli alan değeri en en {{min}} en fazla {{max}} karakterden oluşmalıdır.', dataType: DataType.string},
    {key: 'validation-required', value: '\'{{name}}\' isimli alan boş bırakılamaz.', dataType: DataType.string},
    {key: 'error-page-title', value: 'Bir Hata Oluştu', dataType: DataType.string},
    {key: 'error-message-title', value: 'Hata Mesajı', dataType: DataType.string},
    {key: 'ignore-error', value: 'Hatayı Yoksay', dataType: DataType.string},
    {key: 'reload-application', value: 'Uygulamayı Yeniden Yükle', dataType: DataType.string},
    {key: 'connection-error-title', value: 'İnternet Bağlantısı Bulunamadı', dataType: DataType.string},
    {key: 'connection-error-content', value: 'İnternet bağlantısı bulunamadı. Lütfen bağlantınızı kontrol ediniz. Bağlantı sağlandığı zaman kaldığınız yerden devam edebilirsiniz.', dataType: DataType.string},
    {key: 'undefined-loader-text', value: 'Bilinmeyen yükleme...', dataType: DataType.string},
    {key: 'application-loader-title', value: 'Bekleyen Yükleme(ler) mevcut', dataType: DataType.string},
    {key: 'footer-repository-link-title', value: 'repository', dataType: DataType.string},
    {key: 'footer-repository-link-text', value: 'repository', dataType: DataType.string},
    {key: 'select-app-language', value: 'Dil Seçimi', dataType: DataType.string},
    {key: 'data-transfer', value: 'Veri Aktarımı', dataType: DataType.string},
    {key: 'export-data', value: 'Dışarı Aktar', dataType: DataType.string},
    {key: 'export-excel-file-name', value: 'gorev-listesi', dataType: DataType.string},
    {key: 'export-excel-worksheet-name', value: 'Görev Listesi', dataType: DataType.string},
    {key: 'todo-add-form-job-title-label', value: 'Göre Adı', dataType: DataType.string},
    {key: 'todo-add-form-job-pritiory-label', value: 'Görev Önceliği', dataType: DataType.string},
    {key: 'todo-add-form-dublicate-error-title', value: 'Hata!', dataType: DataType.string},
    {key: 'todo-add-form-dublicate-error-', value: 'Eklemek istediğiniz görev daha önce listeye eklenmiştir. Lütfen farklı bir görev tanımı deneyiniz.', dataType: DataType.string},
    {key: 'todo-add-form-submit-text', value: 'Oluştur', dataType: DataType.string},
    {key: 'todo-add-form-job-priority-chose', value: 'Seçiniz', dataType: DataType.string},
    {key: 'todo-add-form-title', value: 'Yeni Görev Oluştur', dataType: DataType.string}
] as LanguageLocalizationModel[];

const localizationsEn = [
    {key: 'meta-default-title', value: 'Serkan DOĞANBAŞ | Rise TODO App', dataType: DataType.string},
    {key: 'meta-default-keyword', value: 'todo, todo app, serkan doğanbaş', dataType: DataType.string},
    {key: 'meta-default-description', value: 'Rise Frontend Assessment Project.', dataType: DataType.string},
    {key: 'meta-default-abstract', value: 'Rise Frontend Assessment Project.', dataType: DataType.string},
    {key: 'fetch-todo-priority-list', value: 'Receiving priority data from server...', dataType: DataType.string},
    {key: 'validation-required', value: 'The field named \'{{name}}\' cannot be left blank.', dataType: DataType.string},
    {key: 'validation-string-min', value: 'The field value \'{{name}}\' must be at least {{min}} characters.', dataType: DataType.string},
    {key: 'validation-string-max', value: 'The field value named \'{{name}}\' must be a maximum of {{max}} characters.', dataType: DataType.string},
    {key: 'validation-string-length', value: 'The field value named \'{{name}}\' must be at least {{min}} and at most {{max}} characters.', dataType: DataType.string},
    {key: 'validation-required', value: 'The field named \'{{name}}\' cannot be left blank.', dataType: DataType.string},
    {key: 'error-page-title', value: 'Something Went Wrong', dataType: DataType.string},
    {key: 'error-message-title', value: 'Error Message', dataType: DataType.string},
    {key: 'ignore-error', value: 'Ignore Error', dataType: DataType.string},
    {key: 'reload-application', value: 'Reload Application', dataType: DataType.string},
    {key: 'connection-error-title', value: 'Internet Connection Not Found', dataType: DataType.string},
    {key: 'connection-error-content', value: 'Internet connection not found. Please check your connection. Once the connection is established, you can continue where you left off.', dataType: DataType.string},
    {key: 'undefined-loader-text', value: 'Unknown install...', dataType: DataType.string},
    {key: 'application-loader-title', value: 'Pending Download(s) available', dataType: DataType.string},
    {key: 'footer-repository-link-title', value: 'repository', dataType: DataType.string},
    {key: 'footer-repository-link-text', value: 'repository', dataType: DataType.string},
    {key: 'select-app-language', value: 'Select Language', dataType: DataType.string},
    {key: 'data-transfer', value: 'Data Transfer', dataType: DataType.string},
    {key: 'export-data', value: 'Export Data', dataType: DataType.string},
    {key: 'export-excel-file-name', value: 'job-list', dataType: DataType.string},
    {key: 'export-excel-worksheet-name', value: 'Job List', dataType: DataType.string},
    {key: 'todo-add-form-job-title-label', value: 'Job Name', dataType: DataType.string},
    {key: 'todo-add-form-job-pritiory-label', value: 'Job Priority', dataType: DataType.string},
    {key: 'todo-add-form-dublicate-error-title', value: 'Error!', dataType: DataType.string},
    {key: 'todo-add-form-dublicate-error-', value: 'The task you want to add has already been added to the list. Please try a different job description.', dataType: DataType.string},
    {key: 'todo-add-form-submit-text', value: 'Create', dataType: DataType.string},
    {key: 'todo-add-form-job-priority-chose', value: 'Choose', dataType: DataType.string},
    {key: 'todo-add-form-title', value: 'Create New Job', dataType: DataType.string}
] as LanguageLocalizationModel[];

export {localizationsTr, localizationsEn};
